include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_web_libraries_in_flutter: false

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
