name: wallet_core_web
description: A new Flutter project.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.17.0-0.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  inject_js: ^2.0.0
  js: ^0.6.4
  protobuf: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - web/assets/
